language: cpp

sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - hvr-ghc
    packages:
      - g++-4.8
      - libboost-all-dev
      - software-properties-common
      - cabal-install
      - ghc

before_script:
  - cabal update
  - cabal install shake

script:
  - mkdir -p .shake
  - ghc --make Build.hs -rtsopts -with-rtsopts=-I0 -outputdir=.shake -Dcxx='"g++"' -o make
  - ./make
